### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by panda2134** [panda2134/CompactLavaGenerator#1]
- [x] Rewrite some code in MultiblockHelper
- [x] Rewrite some code in CLGHammer&CLGController
- [x] Fix the bug of network ( @ueyudiud could you please give me some help when you're free? )
- [x] Add generator and output hatch
- [x] Support changing output energy unit
- [x] Suppert EU,RF&FZ Charge
- [x] fix the bug of connecting Thermal Dynamics Pipes
- [x] put the mod on Minecraft Forum and Curse

**Comment by ueyudiud** [comment]
The render needn't update with a too large range.

**Comment by KaedeLen** [comment]
why you are so diao

**Comment by panda2134** [comment]
@elctove when you register the Github account >.<

**Comment by KaedeLen** [comment]
@panda2134 8.12

**Comment by panda2134** [comment]
working on rf and charge compat

**Comment by 3TUSK** [comment]
Please support ImagFlux from [AcademyCraft](https://github.com/LambdaInnovation/AcademyCraft) XD

**Comment by panda2134** [comment]
as it supports EU and RF,it's not necessary to support ImagFlux

**Comment by panda2134** [comment]
Finally fixed the bug of extracting RF
:-D
